version: "3"
services:
  tools:
    build: .
    stdin_open: true
    tty: true
    environment:
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    volumes:
      - ./work:/work:rw
